### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by darkman242** [DrozmotiX/ioBroker.esphome#128]
Ich habe den den Adapter in der Version 0.2.4 erneut installiert um eine aktuelle ESPhome-Version zu bekommen. Dies hat bis zur Version 2022.3.0 funktioniert. Nun kann ich zwar den Adapter aktualisieren (aktuell auf die 2022.03.02, aber wenn ich im Dashboard ein Update der ESPs installieren will kommt nachfolgende Meldung.

`INFO Reading configuration /opt/iobroker/iobroker-data/esphome.0/wassertank.yaml...
INFO Generating C++ source...
INFO Compiling app...
sh: 0: getcwd() failed: No such file or directory
Error: Traceback (most recent call last):
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/__main__.py", line 121, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/__main__.py", line 60, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/maintenance.py", line 44, in on_platformio_start
    telemetry.on_command()
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/telemetry.py", line 292, in on_command
    resend_backuped_reports()
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/telemetry.py", line 443, in resend_backuped_reports
    tm = app.get_state_item("telemetry", {})
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/app.py", line 194, in get_state_item
    with State() as state:
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/app.py", line 94, in __init__
    core_dir = ProjectConfig.get_instance().get("platformio", "core_dir")
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/project/config.py", line 379, in get_instance
    path = ProjectConfig.get_default_path() if path is None else path
  File "/opt/iobroker/node_modules/iobroker.esphome/python_modules/lib/python3.9/site-packages/platformio/project/config.py", line 81, in get_default_path
    os.getcwd(), "platformio.ini"
FileNotFoundError: [Errno 2] No such file or directory

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================`

**Comment by DutchmanNL** [comment]
> Hi, nein habe ich nicht. Ich habe den Adapter einfach gelöscht und neu installiert. Danach funktioniert es natürlich. Vlt kannst du es trotzdem nachvollziehen.

leider nein: "FileNotFoundError: [Errno 2] No such file or directory"

da haben Dateien gefehlt oder die Berechtigungen nicht gestimmt, beim einer neu Installation des adapter wird dies ne gesetzt also wird schwierig noch zu ermitteln was die Ursache war :/

**Comment by boeckp** [comment]
Hatte das gleiche Problem, ein "iob fix" stellte alles wieder richtig. 

> > Hi, nein habe ich nicht. Ich habe den Adapter einfach gelöscht und neu installiert. Danach funktioniert es natürlich. Vlt kannst du es trotzdem nachvollziehen.
> 
> 
> 
> leider nein: "FileNotFoundError: [Errno 2] No such file or directory"
> 
> 
> 
> da haben Dateien gefehlt oder die Berechtigungen nicht gestimmt, beim einer neu Installation des adapter wird dies ne gesetzt also wird schwierig noch zu ermitteln was die Ursache war :/
