### ISSUE TITLE
Please update your pillow installation to 10.1.0. (pip install "pillow==10.1.0")

### ISSUE THREAD

**Issue by stmb-100** [DrozmotiX/ioBroker.esphome#199]
Ich bekomme die Fehlermeldung seit ich das Update auf v0.5.0-beta.10 durchgeführt habe., mit der beta.8 hat es noch funktioniert

**Please update your pillow installation to 10.1.0. (pip install "pillow==10.1.0")**

das Ausführen von sudo pip install "pillow==10.1.0" hat keine Veraenderung gebracht.

Ich verwende im Code:
font:
  - file: "fonts/arial.ttf"
    id: my_font_10
    size: 10

Bitte um Update des Adapters

Lg
Stefan

**Comment by SimonFischer04** [comment]
https://github.com/DrozmotiX/ioBroker.esphome/issues/188

**Comment by stmb-100** [comment]
Hallo zusammen kann das Problem nur DutchmanNL lösen oder würde es sich auch jemand anders zutrauen ?

**Comment by SimonFischer04** [comment]
@stmb-100 Fix selbst solt sehr simple sein, habs schnell wieder umgebaut. Frage ist eher was zuvor das Problem war / warum es auf fixe Version geändert wurden. Try installing directly from Github: [https://github.com/SimonFischer04/ioBroker.esphome/tree/fix/latestpillow](url)

**Comment by SimonFischer04** [comment]
@stmb-100 und wenn du schon so ne frage stellt: würdest du es dir auch selbst zutrauen 😄?

Ist wirklich kein komplexes Problem / fix. Wie schon im letzten comment beschrieben, ein undo von: https://github.com/DrozmotiX/ioBroker.esphome/commit/6600a6aeb9a82fcecc5f848aa72a780d73998402

**Comment by stmb-100** [comment]
@SimonFischer04 Hi wenn ich bis jetzt gewusst hätte was ich wo ändern muss, hätte ich es auch selbst machen können. Hab mich  aber noch nicht so intensiv damit beschäftigt. Jetzt weis ich wo ich es ändern muss. Danke für die Hilfe.

**Comment by SimonFischer04** [comment]
@stmb-100 wahrscheinlich weil das dann mehr "any" als latest version ist - würd nur worken wenn man adapter reinstalled, sonst sieht er die dependency wahrscheinlich schon als satisfied an.

Werds das mal ein wenig mehr testen, wenn ich Zeit hab, aber 👍🏾, dass du einen fix gefunden hast.

**Comment by DutchmanNL** [comment]
> @stmb-100 wahrscheinlich weil das dann mehr "any" als latest version ist - würd nur worken wenn man adapter reinstalled, sonst sieht er die dependency wahrscheinlich schon als satisfied an.
> 
> Werds das mal ein wenig mehr testen, wenn ich Zeit hab, aber 👍🏾, dass du einen fix gefunden hast.

wir können das gleich lesen wir mit dem dashboard fallt mir da ein, also der code ist da müsste nur auch auf das pillow package erweitert werden

**Comment by SimonFischer04** [comment]
> > @stmb-100 wahrscheinlich weil das dann mehr "any" als latest version ist - würd nur worken wenn man adapter reinstalled, sonst sieht er die dependency wahrscheinlich schon als satisfied an.
> > Werds das mal ein wenig mehr testen, wenn ich Zeit hab, aber 👍🏾, dass du einen fix gefunden hast.
> 
> wir können das genau so loesen wie mit dem dashboard fallt mir da ein, also der code ist da müsste nur auch auf das pillow package erweitert werden

Gleicher Gedanke hier. Frage ist nur , ob wir es dem User überlassen in den adapter settings passende versionen beider packages auszuwählen, oder mit https://github.com/DrozmotiX/ioBroker.esphome/pull/183 vorranschreiten.

**Comment by stmb-100** [comment]
Hallo zusammen
hat jemand eine Idee zur Behebung dieser Fehlermeldung, der ESPHome Adapter rebootet immer wieder 
LG
Stefan

esphome.1 | 2024-06-06 07:18:25.823 | error | Cannot read properties of undefined (reading 'toUpperCase')

esphome.1 | 2024-06-06 07:18:25.822 | error | TypeError: Cannot read properties of undefined (reading 'toUpperCase') at EsphomeDescovery.<anonymous> (/Users/nl69zh/Developer/community/opensource/ioBroker.esphome/main.js:321:18) at EsphomeDescovery.emit (node:events:517:28) at EsphomeDescovery.emit (node:domain:489:12) at EsphomeDescovery._response (/opt/iobroker/node_modules/@2colors/esphome-native-api/lib/discovery.js:55:14) at EventEmitter.emit (node:events:517:28) at EventEmitter.emit (node:domain:489:12) at Socket.<anonymous> (/opt/iobroker/node_modules/multicast-dns/index.js:49:43) at Socket.emit (node:events:517:28) at Socket.emit (node:domain:489:12) at UDP.onMessage (node:dgram:942:8)

esphome.1 | 2024-06-06 07:18:25.822 | error | uncaught exception: Cannot read properties of undefined (reading 'toUpperCase')

**Comment by WallE01010** [comment]
Hallo an die Gruppe, ich bin völlig neu hier und hoffe, dass ich keine unnötige Frage stellen. In Summe besitze ich keine wirkliche Erfahrung. Habe bisher kleinere private Projekte auf ESP32 realisiert. Mein Problem:  Ich bekomme nahezu die gleiche Fehlermeldung wie **stmb-100**. Meine Installation ist ebenso v0.5.0-beta.10 und die Fehlermeldung ist leicht anders:

Please update your pillow installation to 10.**2**.0. (pip install "pillow==10.**2**.0")

Gibt es dazu ein Workaround oder ist eine Lösung bereits vorhanden. 

Besten Dank für eine Antwort!

**Comment by SimonFischer04** [comment]
> @stmb-100 Fix selbst solt sehr simple sein, habs schnell wieder umgebaut. Frage ist eher was zuvor das Problem war / warum es auf fixe Version geändert wurden. Try installing directly from Github: [https://github.com/SimonFischer04/ioBroker.esphome/tree/fix/latestpillow](url)

@WallE01010 siehe hier. (und folgende Nachrichten)

**Comment by WallE01010** [comment]
Super, hat funktioniert. Danke

 

 

Beste Grüße,

Christof

 

Dr. Christof Bosbach

Reichenspergerstr. 8

41464 Neuss

 

Von: Simon Fischer ***@***.***> 
Gesendet: Mittwoch, 6. November 2024 21:28
An: DrozmotiX/ioBroker.esphome ***@***.***>
Cc: WallE01010 ***@***.***>; Mention ***@***.***>
Betreff: Re: [DrozmotiX/ioBroker.esphome] Please update your pillow installation to 10.1.0. (pip install "pillow==10.1.0") (Issue #199)

 

@stmb-100 <https://github.com/stmb-100>  Fix selbst solt sehr simple sein, habs schnell wieder umgebaut. Frage ist eher was zuvor das Problem war / warum es auf fixe Version geändert wurden. Try installing directly from Github: https://github.com/SimonFischer04/ioBroker.esphome/tree/fix/latestpillow

@WallE01010 <https://github.com/WallE01010>  siehe hier. (und folgende Nachrichten)

**Comment by SaschaKihm** [comment]
Hi zusammen wie kann ich das fix auf meinem ioBroker einspielen?

**Comment by SimonFischer04** [comment]
> https://github.com/SimonFischer04/ioBroker.esphome/tree/fix/latestpillow

von Github installieren: https://github.com/SimonFischer04/ioBroker.esphome/tree/fix/latestpillow
