### ISSUE TITLE
Cannot read properties of undefined (reading 'toUpperCase')

### ISSUE THREAD

**Issue by stmb-100** [DrozmotiX/ioBroker.esphome#207]
Hallo zusammen
hat jemand eine Idee zur Behebung dieser Fehlermeldung, der ESPHome Adapter rebootet immer wieder
LG
Stefan

esphome.1 | 2024-06-06 07:18:25.823 | error | Cannot read properties of undefined (reading 'toUpperCase')

esphome.1 | 2024-06-06 07:18:25.822 | error | TypeError: Cannot read properties of undefined (reading 'toUpperCase') at EsphomeDescovery. (/Users/nl69zh/Developer/community/opensource/ioBroker.esphome/main.js:321:18) at EsphomeDescovery.emit (node:events:517:28) at EsphomeDescovery.emit (node:domain:489:12) at EsphomeDescovery._response (/opt/iobroker/node_modules/@2colors/esphome-native-api/lib/discovery.js:55:14) at EventEmitter.emit (node:events:517:28) at EventEmitter.emit (node:domain:489:12) at Socket. (/opt/iobroker/node_modules/multicast-dns/index.js:49:43) at Socket.emit (node:events:517:28) at Socket.emit (node:domain:489:12) at UDP.onMessage (node:dgram:942:8)

esphome.1 | 2024-06-06 07:18:25.822 | error | uncaught exception: Cannot read properties of undefined (reading 'toUpperCase')

**Comment by DutchmanNL** [comment]
Sind das die einzigen Meldungen im log oder kommt da noch mehr?

Sieht noch einem Modul Fehler aus, was für ein Betriebssystem wird eingesetzt?

**Comment by stmb-100** [comment]
Docker Container (buanet/iobroker:latest) auf Debian Linux 5.10.0
ESPHome Adapter : 0.5.0 beta 10

Weitere Fehler habe ich im Moment im Adapter nicht gefunden.
LG
Stefan

**Comment by SimonFischer04** [comment]
Bitte Log mal auf Debug Level umstellen.

Schaut aber aus als wär die MAC adresse aus Gründen undefined: https://github.dev/DrozmotiX/ioBroker.esphome/blob/main/main.js#L321

**Comment by Morris124** [comment]
Ich habe nach dem Switch auf dein Fork die meisten. einer Fehler beseitigen können, was bleibt ist der oben gennante Fehler.

**Comment by SimonFischer04** [comment]
@Morris124 

Hab einen neuen branch mit einigen fixes. Bitte testen: https://github.com/SimonFischer04/ioBroker.esphome/tree/beta
