### ISSUE TITLE
Dashboard not starting

### ISSUE THREAD

**Issue by Bavarialex** [DrozmotiX/ioBroker.esphome#220]
As stated in log, ESPHome tries to update unsuccessfully to 2024.11.0b2.
Dashboard not loading.

Log:
`Fatal error starting ESPHomeDashboard | 
Error: Command failed with exit code 1: /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.0.1 
ERROR: Cannot install esphome==2024.11.0b2 and pillow==10.0.1 because these package versions have conflicting dependencies. 
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts 
[notice] A new release of pip is available: 23.2.1 -> 24.3.1 
[notice] To update, run: /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install --upgrade pip 
Collecting esphome==2024.11.0b2 
Obtaining dependency information for esphome==2024.11.0b2 from https://files.pythonhosted.org/packages/a7/70/550de87c40fde85418f86aa97a7bad4cc19c9bcfa111d76e4097d71f186f/esphome-2024.11.0b2-py3-none-any.whl.metadata Using cached esphome-2024.11.0b2-py3-none-any.whl.metadata (3.5 kB) 
Requirement already satisfied: pillow==10.0.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (10.0.1) 
Requirement already satisfied: cryptography==43.0.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (43.0.0) 
Requirement already satisfied: voluptuous==0.14.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.14.2)
Collecting PyYAML==6.0.2 (from esphome==2024.11.0b2) Obtaining dependency information for PyYAML==6.0.2 from https://files.pythonhosted.org/packages/75/e4/2c27590dfc9992f73aabbeb9241ae20220bd9452df27483b6e56d3975cc5/PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata 
Using cached PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB) 
Requirement already satisfied: paho-mqtt==1.6.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.6.1) 
Requirement already satisfied: colorama==0.4.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.4.6) 
Requirement already satisfied: icmplib==3.0.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.0.4) 
Requirement already satisfied: tornado==6.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (6.4) 
Requirement already satisfied: tzlocal==5.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (5.2) 
Requirement already satisfied: tzdata>=2021.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (2023.3) 
Requirement already satisfied: pyserial==3.5 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.5) 
Collecting platformio==6.1.16 (from esphome==2024.11.0b2) Using cached platformio-6.1.16.tar.gz (239 kB) 
Installing build dependencies: started Installing build dependencies: finished with status 'done' 
Getting requirements to build wheel: started 
Getting requirements to build wheel: finished with status 'done' 
Preparing metadata (pyproject.toml): started Preparing metadata (pyproject.toml): finished with status 'done' 
Requirement already satisfied: esptool==4.7.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (4.7.0) 
Requirement already satisfied: click==8.1.7 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (8.1.7) 
Collecting esphome-dashboard==20241025.0 (from esphome==2024.11.0b2) Obtaining dependency information for esphome-dashboard==20241025.0 from https://files.pythonhosted.org/packages/6a/28/1d9536f7aff103a1609f6148f243ae98659d9bb597f086501bec384ae43b/esphome_dashboard-20241025.0-py3-none-any.whl.metadata 
Using cached esphome_dashboard-20241025.0-py3-none-any.whl.metadata (1.0 kB) 
Requirement already satisfied: aioesphomeapi==24.6.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (24.6.2) 
Requirement already satisfied: zeroconf==0.132.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.132.2) 
Requirement already satisfied: puremagic==1.27 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.27) 
Requirement already satisfied: ruamel.yaml==0.18.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.18.6) 
Collecting glyphsets==1.0.0 (from esphome==2024.11.0b2) 
Obtaining dependency information for glyphsets==1.0.0 from https://files.pythonhosted.org/packages/5b/2f/722ca9dd8b4745ae58a036ad4223cb8c32ccd1a0e1b6e9b4f3f3afaed6cb/glyphsets-1.0.0-py3-none-any.whl.metadata 
Using cached glyphsets-1.0.0-py3-none-any.whl.metadata (12 kB) 
INFO: pip is looking at multiple versions of esphome to determine which version is compatible with other requirements. This could take a while. The conflict is caused by: The user requested pillow==10.0.1 esphome 2024.11.0b2 depends on pillow==10.4.0 
To fix this you could try to: 1. loosen the range of package versions you've specified 
2. remove package versions to allow pip attempt to solve the dependency conflict | 

Error: Command failed with exit code 1: /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.0.1 
ERROR: Cannot install esphome==2024.11.0b2 and pillow==10.0.1 because these package versions have conflicting dependencies. 
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts 
[notice] A new release of pip is available: 23.2.1 -> 24.3.1 
[notice] To update, run: /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install --upgrade pip Collecting esphome==2024.11.0b2 
Obtaining dependency information for esphome==2024.11.0b2 from https://files.pythonhosted.org/packages/a7/70/550de87c40fde85418f86aa97a7bad4cc19c9bcfa111d76e4097d71f186f/esphome-2024.11.0b2-py3-none-any.whl.metadata 
Using cached esphome-2024.11.0b2-py3-none-any.whl.metadata (3.5 kB) 
Requirement already satisfied: pillow==10.0.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (10.0.1) 
Requirement already satisfied: cryptography==43.0.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (43.0.0) 
Requirement already satisfied: voluptuous==0.14.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.14.2) 
Collecting PyYAML==6.0.2 (from esphome==2024.11.0b2) Obtaining dependency information for PyYAML==6.0.2 from https://files.pythonhosted.org/packages/75/e4/2c27590dfc9992f73aabbeb9241ae20220bd9452df27483b6e56d3975cc5/PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata 
Using cached PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB) 
Requirement already satisfied: paho-mqtt==1.6.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.6.1) 
Requirement already satisfied: colorama==0.4.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.4.6) 
Requirement already satisfied: icmplib==3.0.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.0.4) 
Requirement already satisfied: tornado==6.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (6.4) 
Requirement already satisfied: tzlocal==5.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (5.2) 
Requirement already satisfied: tzdata>=2021.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (2023.3) 
Requirement already satisfied: pyserial==3.5 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.5) 
Collecting platformio==6.1.16 (from esphome==2024.11.0b2) Using cached platformio-6.1.16.tar.gz (239 kB) 
Installing build dependencies: started 
Installing build dependencies: finished with status 'done' 
Getting requirements to build wheel: started 
Getting requirements to build wheel: finished with status 'done' 
Preparing metadata (pyproject.toml): started Preparing metadata (pyproject.toml): finished with status 'done' 
Requirement already satisfied: esptool==4.7.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (4.7.0) 
Requirement already satisfied: click==8.1.7 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (8.1.7) 
Collecting esphome-dashboard==20241025.0 (from esphome==2024.11.0b2) Obtaining dependency information for esphome-dashboard==20241025.0 from https://files.pythonhosted.org/packages/6a/28/1d9536f7aff103a1609f6148f243ae98659d9bb597f086501bec384ae43b/esphome_dashboard-20241025.0-py3-none-any.whl.metadata 
Using cached esphome_dashboard-20241025.0-py3-none-any.whl.metadata (1.0 kB) 
Requirement already satisfied: aioesphomeapi==24.6.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (24.6.2) 
Requirement already satisfied: zeroconf==0.132.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.132.2) 
Requirement already satisfied: puremagic==1.27 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.27) 
Requirement already satisfied: ruamel.yaml==0.18.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.18.6) 
Collecting glyphsets==1.0.0 (from esphome==2024.11.0b2) 
Obtaining dependency information for glyphsets==1.0.0 from https://files.pythonhosted.org/packages/5b/2f/722ca9dd8b4745ae58a036ad4223cb8c32ccd1a0e1b6e9b4f3f3afaed6cb/glyphsets-1.0.0-py3-none-any.whl.metadata 
Using cached glyphsets-1.0.0-py3-none-any.whl.metadata (12 kB) 
INFO: pip is looking at multiple versions of esphome to determine which version is compatible with other requirements. This could take a while. The conflict is caused by: The user requested pillow==10.0.1 esphome 2024.11.0b2 depends on pillow==10.4.0 
To fix this you could try to: 1. loosen the range of package versions you've specified 2. remove package versions to allow pip attempt to solve the dependency conflict at makeError (file:///opt/iobroker/node_modules/autopy/node_modules/execa/lib/error.js:60:11) at handlePromise (file:///opt/iobroker/node_modules/autopy/node_modules/execa/index.js:124:26) at processTicksAndRejections (node:internal/process/task_queues:95:5) at $df9eabe9bda49ea8$export$e522f41234ab669a (file:///opt/iobroker/node_modules/autopy/src/index.ts:257:13) at Esphome.espHomeDashboard (/Users/nl69zh/Developer/community/opensource/ioBroker.esphome/main.js:180:7) at Esphome.onReady (/opt/iobroker/node_modules/iobroker.esphome/main.js:66:4)`

After updating pip as told, the error still persists:
new log:
`Fatal error starting ESPHomeDashboard | Error: Command failed with exit code 1: /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.0.1 ERROR: Cannot install esphome==2024.11.0b2 and pillow==10.0.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts Collecting esphome==2024.11.0b2 Using cached esphome-2024.11.0b2-py3-none-any.whl.metadata (3.5 kB) Requirement already satisfied: pillow==10.0.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (10.0.1) Requirement already satisfied: cryptography==43.0.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (43.0.0) Requirement already satisfied: voluptuous==0.14.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.14.2) Collecting PyYAML==6.0.2 (from esphome==2024.11.0b2) Using cached PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB) Requirement already satisfied: paho-mqtt==1.6.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.6.1) Requirement already satisfied: colorama==0.4.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.4.6) Requirement already satisfied: icmplib==3.0.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.0.4) Requirement already satisfied: tornado==6.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (6.4) Requirement already satisfied: tzlocal==5.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (5.2) Requirement already satisfied: tzdata>=2021.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (2023.3) Requirement already satisfied: pyserial==3.5 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.5) Collecting platformio==6.1.16 (from esphome==2024.11.0b2) Using cached platformio-6.1.16.tar.gz (239 kB) Installing build dependencies: started Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'done' Preparing metadata (pyproject.toml): started Preparing metadata (pyproject.toml): finished with status 'done' Requirement already satisfied: esptool==4.7.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (4.7.0) Requirement already satisfied: click==8.1.7 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (8.1.7) Collecting esphome-dashboard==20241025.0 (from esphome==2024.11.0b2) Using cached esphome_dashboard-20241025.0-py3-none-any.whl.metadata (1.0 kB) Requirement already satisfied: aioesphomeapi==24.6.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (24.6.2) Requirement already satisfied: zeroconf==0.132.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.132.2) Requirement already satisfied: puremagic==1.27 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.27) Requirement already satisfied: ruamel.yaml==0.18.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.18.6) Collecting glyphsets==1.0.0 (from esphome==2024.11.0b2) Using cached glyphsets-1.0.0-py3-none-any.whl.metadata (12 kB) INFO: pip is looking at multiple versions of esphome to determine which version is compatible with other requirements. This could take a while. The conflict is caused by: The user requested pillow==10.0.1 esphome 2024.11.0b2 depends on pillow==10.4.0 To fix this you could try to: 1. loosen the range of package versions you've specified 2. remove package versions to allow pip to attempt to solve the dependency conflict | Error: Command failed with exit code 1: /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.0.1 ERROR: Cannot install esphome==2024.11.0b2 and pillow==10.0.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts Collecting esphome==2024.11.0b2 Using cached esphome-2024.11.0b2-py3-none-any.whl.metadata (3.5 kB) Requirement already satisfied: pillow==10.0.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (10.0.1) Requirement already satisfied: cryptography==43.0.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (43.0.0) Requirement already satisfied: voluptuous==0.14.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.14.2) Collecting PyYAML==6.0.2 (from esphome==2024.11.0b2) Using cached PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB) Requirement already satisfied: paho-mqtt==1.6.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.6.1) Requirement already satisfied: colorama==0.4.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.4.6) Requirement already satisfied: icmplib==3.0.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.0.4) Requirement already satisfied: tornado==6.4 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (6.4) Requirement already satisfied: tzlocal==5.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (5.2) Requirement already satisfied: tzdata>=2021.1 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (2023.3) Requirement already satisfied: pyserial==3.5 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (3.5) Collecting platformio==6.1.16 (from esphome==2024.11.0b2) Using cached platformio-6.1.16.tar.gz (239 kB) Installing build dependencies: started Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'done' Preparing metadata (pyproject.toml): started Preparing metadata (pyproject.toml): finished with status 'done' Requirement already satisfied: esptool==4.7.0 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (4.7.0) Requirement already satisfied: click==8.1.7 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (8.1.7) Collecting esphome-dashboard==20241025.0 (from esphome==2024.11.0b2) Using cached esphome_dashboard-20241025.0-py3-none-any.whl.metadata (1.0 kB) Requirement already satisfied: aioesphomeapi==24.6.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (24.6.2) Requirement already satisfied: zeroconf==0.132.2 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.132.2) Requirement already satisfied: puremagic==1.27 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (1.27) Requirement already satisfied: ruamel.yaml==0.18.6 in /home/iobroker/.cache/autopy/venv/esphome/lib/python3.11/site-packages (from esphome==2024.11.0b2) (0.18.6) Collecting glyphsets==1.0.0 (from esphome==2024.11.0b2) Using cached glyphsets-1.0.0-py3-none-any.whl.metadata (12 kB) INFO: pip is looking at multiple versions of esphome to determine which version is compatible with other requirements. This could take a while. The conflict is caused by: The user requested pillow==10.0.1 esphome 2024.11.0b2 depends on pillow==10.4.0 To fix this you could try to: 1. loosen the range of package versions you've specified 2. remove package versions to allow pip to attempt to solve the dependency conflict at makeError (file:///opt/iobroker/node_modules/autopy/node_modules/execa/lib/error.js:60:11) at handlePromise (file:///opt/iobroker/node_modules/autopy/node_modules/execa/index.js:124:26) at processTicksAndRejections (node:internal/process/task_queues:95:5) at $df9eabe9bda49ea8$export$e522f41234ab669a (file:///opt/iobroker/node_modules/autopy/src/index.ts:257:13) at Esphome.espHomeDashboard (/Users/nl69zh/Developer/community/opensource/ioBroker.esphome/main.js:180:7) at Esphome.onReady (/opt/iobroker/node_modules/iobroker.esphome/main.js:66:4)`

**Versions:**  
- proxmox vm debian12
- nodejs v20.18.0
- npm10.8.2
- Adapter 0.5.0 beta 10

 - Installation Method: github ...

**Comment by Bavarialex** [comment]
Rafal, there is an error in your script, or on the ESPHome-side

giving a manual
```
sudo /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.4.0
```
does the job...  :-)

Cheers,
Alex

**Comment by SimonFischer04** [comment]
> Rafal, there is either an error in your script, or on the ESPHome-side
> 
> giving a manual
> ```
> sudo /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.4.0
> ```
> does the job...  :-)
> 
> Cheers,
> Alex

Basic problem is already known here. Unfortunately esphome quite often changes the required pillow version. Forcing updates to the adapter over and over again.
Same problem when updating, not just installing the adapter new. F.e. see: https://github.com/DrozmotiX/ioBroker.esphome/issues/199
To actually resolve this i think its best to proceed with: #183, so we always have a defined pillow version and dashboard version per adapter version, that should work.

Ps: You should not use sudo! This messes up permissions on linux systems.

**Comment by diamand2k22** [comment]
> > Rafal, there is either an error in your script, or on the ESPHome-side
> > giving a manual
> > ```
> > sudo /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.4.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > does the job...  :-)
> > Cheers,
> > Alex
> 
> Basic problem is already known here. Unfortunately esphome quite often changes the required pillow version. Forcing updates to the adapter over and over again. Same problem when updating, not just installing the adapter new. F.e. see: #199 To actually resolve this i think its best to proceed with: #183, so we always have a defined pillow version and dashboard version per adapter version, that should work.
> 
> Ps: You should not use sudo, if not required! This messes up permissions on linux systems.

Funktioniert das auch beim Raspberry PI ? 
Hab das selbe Problem, dass nach einem Update das Dashboard nicht mehr geladen werden kann :-/

**Comment by SimonFischer04** [comment]
> > > Rafal, there is either an error in your script, or on the ESPHome-side
> > > giving a manual
> > > ```
> > > sudo /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.4.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > does the job...  :-)
> > > Cheers,
> > > Alex
> > 
> > 
> > Basic problem is already known here. Unfortunately esphome quite often changes the required pillow version. Forcing updates to the adapter over and over again. Same problem when updating, not just installing the adapter new. F.e. see: #199 To actually resolve this i think its best to proceed with: #183, so we always have a defined pillow version and dashboard version per adapter version, that should work.
> > Ps: You should not use sudo, if not required! This messes up permissions on linux systems.
> 
> Funktioniert das auch beim Raspberry PI ? Hab das selbe Problem, dass nach einem Update das Dashboard nicht mehr geladen werden kann :-/

@Bavarialex kleine Korrektur. Richtiger Branch notwendig:
https://github.com/SimonFischer04/ioBroker.esphome/tree/fix/latestpillow

**Comment by Bavarialex** [comment]
@SimonFischer04 , sorry, du hast recht, den meinte ich...

**Comment by SimonFischer04** [comment]
> du

no Problem

**Comment by diamand2k22** [comment]
> > > > Rafal, there is either an error in your script, or on the ESPHome-side
> > > > giving a manual
> > > > ```
> > > > sudo /home/iobroker/.cache/autopy/venv/esphome/bin/python3 -m pip install esphome==2024.11.0b2 pillow==10.4.0
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > does the job...  :-)
> > > > Cheers,
> > > > Alex
> > > 
> > > 
> > > Basic problem is already known here. Unfortunately esphome quite often changes the required pillow version. Forcing updates to the adapter over and over again. Same problem when updating, not just installing the adapter new. F.e. see: #199 To actually resolve this i think its best to proceed with: #183, so we always have a defined pillow version and dashboard version per adapter version, that should work.
> > > Ps: You should not use sudo, if not required! This messes up permissions on linux systems.
> > 
> > 
> > Funktioniert das auch beim Raspberry PI ? Hab das selbe Problem, dass nach einem Update das Dashboard nicht mehr geladen werden kann :-/
> 
> @Bavarialex kleine Korrektur. Richtiger Branch notwendig: https://github.com/SimonFischer04/ioBroker.esphome/tree/fix/latestpillow

Über den Branch hat es funktioniert, top, danke euch für die schnelle Hilfe 👍🏻🍻

**Comment by Bavarialex** [comment]
0.6.1 working perfect!
Well done! :-)
